version: '3'
services:
  app:
    #build: .
    image: edsoncabrera/api-caso02:latest
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - neo4j
    command: npm start
    networks:
      default_network:
        ipv4_address: 172.19.0.4  # IP fija para la aplicación

  redis:
    image: redis/redis-stack:latest
    container_name: redis01
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      default_network:
        ipv4_address: 172.19.0.3  # IP fija para Redis

  neo4j:
    image: neo4j:latest
    container_name: neo01
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
    networks:
      default_network:
        ipv4_address: 172.19.0.2  # IP fija para Neo4j

networks:
  default_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16  # Cambia a una subred no usada

